import type { NextPage } from 'next';
import Head from 'next/head';
import { cardList } from '../components/home/card_list/card_list';
import Carousel from '../components/home/carousel/carousel';
import styles from '../styles/home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Skilled Kiwi || I need or I am</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Carousel cardList={cardList} />
    </div>
  );
};

export default Home;
