import type { NextPage } from 'next';
import Head from 'next/head';
import Carousel from '../components/home/carousel/carousel';
import styles from '../styles/home.module.css';

const Home: NextPage = () => {
  const cardList = [
    {
      bg: '/img/card01.jpg',
      msg: () => (
        <div>
          I need a hand.
          <br />
          <b>Skilled hands!</b>
          <div>
            <button>Find Someone to help</button>
          </div>
        </div>
      ),
    },
    {
      bg: '/img/card02.jpg',
      msg: () => (
        <div>
          <b>Skilled Kiwis</b>
          <br />
          help each other
          <br />
          in the community
          <div>
            <button>Find Requests</button>
            <button>Post a Request</button>
          </div>
        </div>
      ),
    },
    {
      bg: '/img/card03.jpg',
      msg: () => (
        <div>
          Earn extra income
          <br />
          in your spare time.
          <br />
          <b>We need you!</b>
          <div>
            <button>Make extra money</button>
          </div>
        </div>
      ),
    },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Skilled Kiwi || I need or I am</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Carousel cardList={cardList} />
    </div>
  );
};

export default Home;
