import type { NextPage } from 'next';
import Head from 'next/head';
import { cardList } from '../components/home/card_list/card_list';
import Carousel from '../components/home/carousel/carousel';
import styles from '../styles/home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Skilled Kiwi || I need or I am</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Carousel cardList={cardList} />
      <div className={styles.contents}>
        <h2>Need hands?</h2>
        <div className={styles.procedure}>
          <span>
            <h3>Post a request</h3>
            <div>
              It is a free and easy to post a request. Fill up a title and little detail for your
              job. You can attach photos if you want.
            </div>
          </span>
          <span>
            <h3>Pick a service provider</h3>
            <div>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
              incididunt ut labore et dolore magna aliqua.
            </div>
          </span>
          <span>
            <h3>Contact him / her</h3>
            <div>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
              incididunt ut labore et dolore magna aliqua.
            </div>
          </span>
          <span>
            <h3>Jobs Done</h3>
            <div>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
              incididunt ut labore et dolore magna aliqua.
            </div>
          </span>
        </div>
        <h2>You're skilled!</h2>
        <div className={styles.procedure}>
          <span>
            <h3>Pick a request</h3>
            <div>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
              incididunt ut labore et dolore magna aliqua.
            </div>
          </span>
          <span>
            <h3>Place a bid</h3>
            <div>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
              incididunt ut labore et dolore magna aliqua.
            </div>
          </span>
          <span>
            <h3>Contact him / her</h3>
            <div>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
              incididunt ut labore et dolore magna aliqua.
            </div>
          </span>
          <span>
            <h3>Jobs Done</h3>
            <div>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
              incididunt ut labore et dolore magna aliqua.
            </div>
          </span>
        </div>
      </div>
    </div>
  );
};

export default Home;
